<h2>${server_view['hostname']} Status</h2>

<h3>${lang('pastafari', 'network_status', 'Network status')}</h3>

<canvas id="network_status" width="800" height="300"></canvas>

<h3>${lang('pastafari', 'cpu_status', 'Cpu status')}</h3>

<script language="javascript" src="${make_media_url_module('js/chart.min.js', 'pastafari')}"></script>
<script language="javascript">

var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [65, 59, 80, 81, 56, 55, 40]
        },
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};

var options={}

var ctx=document.getElementById("network_status").getContext("2d");
var network_status=new Chart(ctx).Line(data, options);



</script>